#!/bin/bash

. "$HOME"/.local/share/shells/lib/services.sh

DialogType="window" # text
YesNo "Checking packages" "window Do You want to continue?"

case ${UCH} in
    0) echo "Да";;
    1) echo "Нет";;
    255) echo "ESC";;
esac

DialogType="text"
YesNo "Checking packages" "text Do You want to continue?"

case ${UCH} in
    0) echo "Да";;
    1) echo "Нет";;
    255) echo "ESC";;
esac

echo Done