#!/bin/bash

. ./lib_src/services.sh

DialogType="window" # text
yesno "Checking packages" "window Do You want to continue?"

case ${UCH} in
    0) echo "Да";;
    1) echo "Нет";;
    255) echo "ESC";;
esac

DialogType="text"
yesno "Checking packages" "text Do You want to continue?"

case ${UCH} in
    0) echo "Да";;
    1) echo "Нет";;
    255) echo "ESC";;
esac

echo Done