#!/bin/bash

declare -A textarr

for (( w=0; w<1024; w++ )); do
  textarr[2,$w]="Win 2 TEST $w"
done

for (( w=0; w<2048; w++ )); do
  textarr[3,$w]="Win 2 TEST $w"
done

echo OK

wincount=2
arrsize=0

getarrsize()
{
  arrsize=0
  if [ -z $1 ]; then I=0; N=$wincount;
  else I=$1; N=$1; fi	

  for (( i=I; i<=N; i++ )); do
	for (( j=0;  ; j++ )); do
	  if [ -z "${textarr[$i,$j]}" ]; then break; fi
	done
	let arrsize+=$j  
  done
}

echo "All size=${#textarr[@]}"
#echo "list assos=${!textarr[@]}"

getarrsize 
echo "All arrsize=$arrsize"

getarrsize 0
echo "arrsize 0 =$arrsize"

getarrsize 1
echo "arrsize 1 =$arrsize"

getarrsize 2
echo "arrsize 2 =$arrsize"

getarrsize 3
echo "arrsize 3 =$arrsize"
echo -en > asdf
for (( w=0; w<2048; w++ )); do
  echo "win3[$w]=\"${textarr[3,$w]}\"" >> asdf
done

w=0
while read str ; do
  let w++
  sss=`echo $str | cut -d" " -f 3`
  echo "$w. $sss AAAA SSSSS DDDDD"
done < asdf
