#!/bin/bash
################################################################################
##
## ASPD changer
##
## wocson (c) v. 0.97
##
## Requare: zsh, lftp, mc
##
export LANG=ru_RU.UTF-8
export LC_ALL=ru_RU.UTF-8

WHO=`echo $0 | rev | cut -d "/" -f1 | rev`
LIB=/root/lib
RMT_FS="./test"
LCL_FS="./"

NO_ARGS=0

echo "email"
echo "Command: $1"

if [ $# -eq "$NO_ARGS" ]; then
  echo "No args"
  exit $E_OPTERROR        # и выйти с кодом ошибки
fi

echo "001"

ADRS="$2"; SUBJ=""; TXTM=""; ATCH="";
#shift

while getopts "a:s:t:" Option; do
  case $Option in
    s) echo "Действие 1: опция - $Option. Номер опции: $OPTIND. Аргумент: $OPTARG";;
    t) echo "Действие 2: опция - $Option. Номер опции: $OPTIND. Аргумент: $OPTARG";;
    a) echo "Действие 3: опция - $Option. Номер опции: $OPTIND. Аргумент: $OPTARG";;
    *) echo "выбран недопустимый ключ."
            exit $E_OPTERROR;;   # ПО-УМОЛЧАНИЮ
  esac
done
shift $(($OPTIND - 1))

echo "007:"

exit

				  echo "e-mail"
				  if [ $# -eq "$NO_ARGS" ];	then
					echo "Аргументы не указаны"
					exit $E_OPTERROR        # и выйти с кодом ошибки
				  fi

				  ADRS="$2"; SUBJ=""; TXTM=""; ATCH="";
				  shift

				  while getopts "a:s:t:" Option; do
					case $Option in
  					  s) SUBJ=$OPTARG;;
  					  t) TXTM=$OPTARG;;
  					  a) ATCH=$OPTARG;;
  					  *) echo "Задан недопустимый ключ."
          					exit $E_OPTERROR;;   # ПО-УМОЛЧАНИЮ
					esac
				  done
				  shift $(($OPTIND - 1))
				  echo "msgmail "$ADRS" "$SUBJ" "$TXTM" "$ATCH""
