.TH "AutoMutex" 3 "Fri Jan 21 2011" "mtlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoMutex \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AutoMutex.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAutoMutex\fP (pthread_mutex_t *m)"
.br
.ti -1c
.RI "\fB~AutoMutex\fP ()"
.br
.ti -1c
.RI "void \fBSetLockStatus\fP (bool b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file AutoMutex.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AutoMutex::AutoMutex (pthread_mutex_t * m)\fC [inline]\fP"
.PP
Definition at line 13 of file AutoMutex.h.
.SS "AutoMutex::~AutoMutex ()\fC [inline]\fP"
.PP
Definition at line 21 of file AutoMutex.h.
.SH "Member Function Documentation"
.PP 
.SS "void AutoMutex::SetLockStatus (bool b)\fC [inline]\fP"
.PP
Definition at line 26 of file AutoMutex.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for mtlib from the source code.
