.TH "mt::AutoMutex" 3 "Fri Jan 21 2011" "mtlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mt::AutoMutex \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AutoMutex.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAutoMutex\fP (\fBMutex\fP &mutex)"
.br
.ti -1c
.RI "\fB~AutoMutex\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file AutoMutex.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mt::AutoMutex::AutoMutex (\fBMutex\fP & mutex)\fC [inline]\fP"
.PP
Definition at line 11 of file AutoMutex.h.
.SS "mt::AutoMutex::~AutoMutex ()\fC [inline]\fP"
.PP
Definition at line 13 of file AutoMutex.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for mtlib from the source code.
