.TH "mt::DataForOrderSafeQueue" 3 "Fri Jan 21 2011" "mtlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mt::DataForOrderSafeQueue \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OrderSafeQueue.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataForOrderSafeQueue\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBData\fP \fBm_data\fP"
.br
.ti -1c
.RI "bool \fBm_state\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Data> class mt::DataForOrderSafeQueue< Data >"

.PP
Definition at line 22 of file OrderSafeQueue.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class Data > \fBmt::DataForOrderSafeQueue\fP< \fBData\fP >::\fBDataForOrderSafeQueue\fP ()\fC [inline]\fP"
.PP
Definition at line 26 of file OrderSafeQueue.h.
.SH "Member Data Documentation"
.PP 
.SS "template<class Data > \fBData\fP \fBmt::DataForOrderSafeQueue\fP< \fBData\fP >::\fBm_data\fP"
.PP
Definition at line 30 of file OrderSafeQueue.h.
.SS "template<class Data > bool \fBmt::DataForOrderSafeQueue\fP< \fBData\fP >::\fBm_state\fP"
.PP
Definition at line 31 of file OrderSafeQueue.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for mtlib from the source code.
