.TH "mt::Logable" 3 "Fri Jan 21 2011" "mtlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mt::Logable \- 
.PP
if you want enable  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Logable.h>\fP
.PP
Inherited by \fBmt::MysqlConnector\fP, \fBmt::smpp::Codec\fP, \fBmt::smpp::CodecFactory\fP, \fBmt::smpp::PduFactory\fP, \fBmt::smpp::SMPPHelper\fP, \fBmt::smpp::SmppNwIf\fP\fC [virtual]\fP, \fBmt::SMPPClient\fP, \fBmt::SMPPServer\fP, \fBmt::TCPSocket\fP, \fBmt::Thread\fP\fC [virtual]\fP, \fBmt::UdpSocket\fP, and \fBmt::XmlConfig\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogable\fP ()"
.br
.ti -1c
.RI "void \fBsetLoggerPrefix\fP (const std::string &prefix)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBLoggerPtr\fP \fBm_logger\fP"
.br
.ti -1c
.RI "std::string \fBm_loggerPrefix\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
if you want enable 
.PP
Definition at line 22 of file Logable.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Logable::Logable ()"
.PP
Definition at line 17 of file Logable.cpp.
.SH "Member Function Documentation"
.PP 
.SS "void mt::Logable::setLoggerPrefix (const std::string & prefix)\fC [inline]\fP"
.PP
Definition at line 30 of file Logable.h.
.SH "Member Data Documentation"
.PP 
.SS "\fBLoggerPtr\fP \fBmt::Logable::m_logger\fP\fC [protected]\fP"
.PP
Definition at line 26 of file Logable.h.
.SS "std::string \fBmt::Logable::m_loggerPrefix\fP\fC [protected]\fP"
.PP
Definition at line 27 of file Logable.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for mtlib from the source code.
