.TH "mt::OrderSafeQueue" 3 "Fri Jan 21 2011" "mtlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mt::OrderSafeQueue \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OrderSafeQueue.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOrderSafeQueue\fP (size_t size=256)"
.br
.ti -1c
.RI "void \fBenlarge\fP (size_t new_sz)"
.br
.ti -1c
.RI "void \fBpush\fP (\fBData\fP, uint32_t position)"
.br
.ti -1c
.RI "\fBData\fP \fBpop\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Data> class mt::OrderSafeQueue< Data >"

.PP
Definition at line 35 of file OrderSafeQueue.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class Data> \fBmt::OrderSafeQueue\fP< \fBData\fP >::\fBOrderSafeQueue\fP (size_t size = \fC256\fP)\fC [inline]\fP"
.PP
Definition at line 63 of file OrderSafeQueue.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class Data> void \fBmt::OrderSafeQueue\fP< \fBData\fP >::enlarge (size_t new_sz)\fC [inline]\fP"
.PP
Definition at line 70 of file OrderSafeQueue.h.
.SS "template<class Data > \fBData\fP \fBmt::OrderSafeQueue\fP< \fBData\fP >::pop ()"
.PP
Definition at line 120 of file OrderSafeQueue.h.
.SS "template<class Data> void \fBmt::OrderSafeQueue\fP< \fBData\fP >::push (\fBData\fP data, uint32_t position)"
.PP
Definition at line 105 of file OrderSafeQueue.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for mtlib from the source code.
