.TH "mt::PolymorphSmartPtr" 3 "Fri Jan 21 2011" "mtlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mt::PolymorphSmartPtr \- 
.PP
Polymorphic pointer with references counting.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SmartPtr.h>\fP
.PP
Inherits \fBmt::SmartPtr< T >\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPolymorphSmartPtr\fP (const \fBSmartPtr\fP< Y > &smart_ptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T, class Y> class mt::PolymorphSmartPtr< T, Y >"
Polymorphic pointer with references counting. 
.PP
Definition at line 270 of file SmartPtr.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T , class Y > \fBmt::PolymorphSmartPtr\fP< T, Y >::\fBPolymorphSmartPtr\fP (const \fBSmartPtr\fP< Y > & smart_ptr)"
.PP
Definition at line 276 of file SmartPtr.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for mtlib from the source code.
