.TH "mt::smpp::BindParams" 3 "Fri Jan 21 2011" "mtlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mt::smpp::BindParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Inspector.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBsysId\fP"
.br
.ti -1c
.RI "\fBBindType\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file Inspector.h.
.SH "Member Data Documentation"
.PP 
.SS "std::string \fBmt::smpp::BindParams::sysId\fP"
.PP
Definition at line 24 of file Inspector.h.
.SS "\fBBindType\fP \fBmt::smpp::BindParams::type\fP"
.PP
Definition at line 25 of file Inspector.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for mtlib from the source code.
