.TH "mt::smpp::ClientConnection" 3 "Fri Jan 21 2011" "mtlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mt::smpp::ClientConnection \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Processor.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClientConnection\fP ()"
.br
.ti -1c
.RI "void \fBSetConnection\fP (\fBBindType\fP type, \fBConnection\fP *conn)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBsystemId\fP"
.br
.ti -1c
.RI "\fBConnection\fP * \fBrv\fP"
.br
.ti -1c
.RI "\fBConnection\fP * \fBtx\fP"
.br
.ti -1c
.RI "\fBConnection\fP * \fBtm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file Processor.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mt::smpp::ClientConnection::ClientConnection ()\fC [inline]\fP"
.PP
Definition at line 52 of file Processor.h.
.SH "Member Function Documentation"
.PP 
.SS "void mt::smpp::ClientConnection::SetConnection (\fBBindType\fP type, \fBConnection\fP * conn)\fC [inline]\fP"
.PP
Definition at line 58 of file Processor.h.
.SH "Member Data Documentation"
.PP 
.SS "\fBConnection\fP* \fBmt::smpp::ClientConnection::rv\fP"
.PP
Definition at line 49 of file Processor.h.
.SS "std::string \fBmt::smpp::ClientConnection::systemId\fP"
.PP
Definition at line 48 of file Processor.h.
.SS "\fBConnection\fP* \fBmt::smpp::ClientConnection::tm\fP"
.PP
Definition at line 51 of file Processor.h.
.SS "\fBConnection\fP* \fBmt::smpp::ClientConnection::tx\fP"
.PP
Definition at line 50 of file Processor.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for mtlib from the source code.
