.TH "mt::smpp::CodecFactory" 3 "Fri Jan 21 2011" "mtlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mt::smpp::CodecFactory \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Codec.h>\fP
.PP
Inherits \fBmt::Logable\fP.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCodecPtr\fP \fBgetCodec\fP (const std::string &from, const std::string &to)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file Codec.h.
.SH "Member Function Documentation"
.PP 
.SS "\fBCodecPtr\fP mt::smpp::CodecFactory::getCodec (const std::string & from, const std::string & to)\fC [static]\fP"
.PP
Definition at line 16 of file Codec.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for mtlib from the source code.
