.TH "mt::smpp::UdhHeader" 3 "Fri Jan 21 2011" "mtlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mt::smpp::UdhHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataTypes.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBlength\fP"
.br
.ti -1c
.RI "char \fBrefNum\fP"
.br
.ti -1c
.RI "char \fBsize\fP"
.br
.ti -1c
.RI "char \fBmsgId\fP"
.br
.ti -1c
.RI "char \fBtotal\fP"
.br
.ti -1c
.RI "char \fBpartNum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 72 of file DataTypes.h.
.SH "Member Data Documentation"
.PP 
.SS "char \fBmt::smpp::UdhHeader::length\fP"
.PP
Definition at line 73 of file DataTypes.h.
.SS "char \fBmt::smpp::UdhHeader::msgId\fP"
.PP
Definition at line 76 of file DataTypes.h.
.SS "char \fBmt::smpp::UdhHeader::partNum\fP"
.PP
Definition at line 78 of file DataTypes.h.
.SS "char \fBmt::smpp::UdhHeader::refNum\fP"
.PP
Definition at line 74 of file DataTypes.h.
.SS "char \fBmt::smpp::UdhHeader::size\fP"
.PP
Definition at line 75 of file DataTypes.h.
.SS "char \fBmt::smpp::UdhHeader::total\fP"
.PP
Definition at line 77 of file DataTypes.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for mtlib from the source code.
