.TH "mt::smpp::Message" 3 "Fri Jan 21 2011" "mtlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mt::smpp::Message \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataTypes.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessage\fP ()"
.br
.ti -1c
.RI "std::string \fBgetSrcSystemId\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCodingScheme\fP \fBcodingScheme\fP"
.br
.ti -1c
.RI "\fBMessageType\fP \fBtype\fP"
.br
.ti -1c
.RI "uint8_t \fBregisteredDelivery\fP"
.br
.ti -1c
.RI "uint32_t \fBid\fP"
.br
.ti -1c
.RI "std::string \fBcontext\fP"
.br
.ti -1c
.RI "std::string \fBfrom\fP"
.br
.ti -1c
.RI "std::string \fBto\fP"
.br
.ti -1c
.RI "std::string \fBbody\fP"
.br
.ti -1c
.RI "uint32_t \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file DataTypes.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mt::smpp::Message::Message ()\fC [inline]\fP"
.PP
Definition at line 49 of file DataTypes.h.
.SH "Member Function Documentation"
.PP 
.SS "std::string mt::smpp::Message::getSrcSystemId ()\fC [inline]\fP"
.PP
Definition at line 65 of file DataTypes.h.
.SH "Member Data Documentation"
.PP 
.SS "std::string \fBmt::smpp::Message::body\fP"
.PP
Definition at line 63 of file DataTypes.h.
.SS "\fBCodingScheme\fP \fBmt::smpp::Message::codingScheme\fP"
.PP
Definition at line 56 of file DataTypes.h.
.SS "std::string \fBmt::smpp::Message::context\fP"
.PP
Definition at line 60 of file DataTypes.h.
.SS "std::string \fBmt::smpp::Message::from\fP"
.PP
Definition at line 61 of file DataTypes.h.
.SS "uint32_t \fBmt::smpp::Message::id\fP"
.PP
Definition at line 59 of file DataTypes.h.
.SS "uint8_t \fBmt::smpp::Message::registeredDelivery\fP"
.PP
Definition at line 58 of file DataTypes.h.
.SS "uint32_t \fBmt::smpp::Message::status\fP"
.PP
Definition at line 64 of file DataTypes.h.
.SS "std::string \fBmt::smpp::Message::to\fP"
.PP
Definition at line 62 of file DataTypes.h.
.SS "\fBMessageType\fP \fBmt::smpp::Message::type\fP"
.PP
Definition at line 57 of file DataTypes.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for mtlib from the source code.
