.TH "mt::smpp::ServerInspector" 3 "Fri Jan 21 2011" "mtlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mt::smpp::ServerInspector \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ServerInspector.h>\fP
.PP
Inherits \fBmt::smpp::Inspector\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBInit\fP ()"
.br
.ti -1c
.RI "\fBServerInspector\fP (\fBXmlConfigPtr\fP cfg)"
.br
.ti -1c
.RI "void \fBNetworkError\fP (\fBSmppNwIf\fP *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file ServerInspector.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mt::smpp::ServerInspector::ServerInspector (\fBXmlConfigPtr\fP cfg)"
.PP
Definition at line 66 of file ServerInspector.cpp.
.SH "Member Function Documentation"
.PP 
.SS "int mt::smpp::ServerInspector::Init ()"
.PP
Definition at line 81 of file ServerInspector.cpp.
.SS "void mt::smpp::ServerInspector::NetworkError (\fBSmppNwIf\fP * smppIf)\fC [virtual]\fP"
.PP
Implements \fBmt::smpp::Inspector\fP.
.PP
Definition at line 14 of file ServerInspector.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for mtlib from the source code.
