.TH "mt::smpp::commonHeader" 3 "Fri Jan 21 2011" "mtlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mt::smpp::commonHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataTypes.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBlength\fP"
.br
.ti -1c
.RI "unsigned int \fBcmd\fP"
.br
.ti -1c
.RI "unsigned int \fBstatus\fP"
.br
.ti -1c
.RI "unsigned int \fBseqN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file DataTypes.h.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int \fBmt::smpp::commonHeader::cmd\fP"
.PP
Definition at line 37 of file DataTypes.h.
.SS "unsigned int \fBmt::smpp::commonHeader::length\fP"
.PP
Definition at line 36 of file DataTypes.h.
.SS "unsigned int \fBmt::smpp::commonHeader::seqN\fP"
.PP
Definition at line 39 of file DataTypes.h.
.SS "unsigned int \fBmt::smpp::commonHeader::status\fP"
.PP
Definition at line 38 of file DataTypes.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for mtlib from the source code.
