.TH "mt::smpp::_RcvBuf" 3 "Fri Jan 21 2011" "mtlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mt::smpp::_RcvBuf \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SmppNwIf.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBbuf\fP [RECBBUFLEN]"
.br
.ti -1c
.RI "struct \fBcommonHeader\fP \fBhdr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file SmppNwIf.h.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t \fBmt::smpp::_RcvBuf::buf\fP[RECBBUFLEN]"
.PP
Definition at line 31 of file SmppNwIf.h.
.SS "struct \fBcommonHeader\fP \fBmt::smpp::_RcvBuf::hdr\fP"
.PP
Definition at line 32 of file SmppNwIf.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for mtlib from the source code.
