.TH "mt::smpp::Utils" 3 "Fri Jan 21 2011" "mtlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mt::smpp::Utils \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Utils.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::vector< \fBMessagePart\fP > * \fBsegmentateSmsBody\fP (const uint8_t *msg, uint32_t len)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file Utils.h.
.SH "Member Function Documentation"
.PP 
.SS "std::vector< \fBMessagePart\fP > * mt::smpp::Utils::segmentateSmsBody (const uint8_t * msg, uint32_t len)\fC [static]\fP"
.PP
Definition at line 16 of file Utils.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for mtlib from the source code.
