.TH "TcpSocketException" 3 "Fri Jan 21 2011" "mtlib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TcpSocketException \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exceptions.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTcpSocketException\fP (char *str)"
.br
.ti -1c
.RI "\fB~TcpSocketException\fP ()  throw ()"
.br
.ti -1c
.RI "const char * \fBwhat\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBe\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file Exceptions.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TcpSocketException::TcpSocketException (char * str)\fC [inline]\fP"
.PP
Definition at line 26 of file Exceptions.h.
.SS "TcpSocketException::~TcpSocketException ()  throw ()\fC [inline]\fP"
.PP
Definition at line 27 of file Exceptions.h.
.SH "Member Function Documentation"
.PP 
.SS "const char* TcpSocketException::what ()\fC [inline]\fP"
.PP
Definition at line 28 of file Exceptions.h.
.SH "Member Data Documentation"
.PP 
.SS "std::string \fBTcpSocketException::e\fP\fC [protected]\fP"
.PP
Definition at line 24 of file Exceptions.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for mtlib from the source code.
