# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_stest.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(977, 509)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.LogWidget = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        self.LogWidget.setFont(font)
        self.LogWidget.setObjectName("LogWidget")
        self.verticalLayout_6.addWidget(self.LogWidget)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_6.addWidget(self.progressBar)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 7, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(5, 5, 5, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.chBoxLogverb = QtWidgets.QCheckBox(self.centralwidget)
        self.chBoxLogverb.setObjectName("chBoxLogverb")
        self.gridLayout_2.addWidget(self.chBoxLogverb, 0, 1, 1, 1)
        self.TestCmdButton = QtWidgets.QPushButton(self.centralwidget)
        self.TestCmdButton.setObjectName("TestCmdButton")
        self.gridLayout_2.addWidget(self.TestCmdButton, 1, 1, 1, 1)
        self.lcdTestCount = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdTestCount.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdTestCount.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdTestCount.setLineWidth(0)
        self.lcdTestCount.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdTestCount.setObjectName("lcdTestCount")
        self.gridLayout_2.addWidget(self.lcdTestCount, 0, 0, 1, 1)
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setObjectName("StartButton")
        self.gridLayout_2.addWidget(self.StartButton, 3, 0, 1, 2)
        self.CloseButton = QtWidgets.QPushButton(self.centralwidget)
        self.CloseButton.setObjectName("CloseButton")
        self.gridLayout_2.addWidget(self.CloseButton, 4, 0, 1, 2)
        self.SelectAllButton = QtWidgets.QPushButton(self.centralwidget)
        self.SelectAllButton.setMinimumSize(QtCore.QSize(82, 0))
        self.SelectAllButton.setObjectName("SelectAllButton")
        self.gridLayout_2.addWidget(self.SelectAllButton, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 6, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.grBoxTest = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grBoxTest.sizePolicy().hasHeightForWidth())
        self.grBoxTest.setSizePolicy(sizePolicy)
        self.grBoxTest.setFlat(False)
        self.grBoxTest.setCheckable(False)
        self.grBoxTest.setObjectName("grBoxTest")
        self.horizontalLayout.addWidget(self.grBoxTest)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 6, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stress Test"))
        self.chBoxLogverb.setText(_translate("MainWindow", "Log verbose"))
        self.TestCmdButton.setText(_translate("MainWindow", "Test / Cmd"))
        self.StartButton.setText(_translate("MainWindow", "Start"))
        self.CloseButton.setText(_translate("MainWindow", "Close"))
        self.SelectAllButton.setText(_translate("MainWindow", "Select All"))
        self.grBoxTest.setTitle(_translate("MainWindow", "Tests"))
