# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tedit.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TEditWindow(object):
    def setupUi(self, TEditWindow):
        TEditWindow.setObjectName("TEditWindow")
        TEditWindow.resize(800, 379)
        self.centralwidget = QtWidgets.QWidget(TEditWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setObjectName("SaveButton")
        self.gridLayout.addWidget(self.SaveButton, 0, 2, 1, 1)
        self.CloseButton = QtWidgets.QPushButton(self.centralwidget)
        self.CloseButton.setObjectName("CloseButton")
        self.gridLayout.addWidget(self.CloseButton, 0, 3, 1, 1)
        self.FileButton = QtWidgets.QPushButton(self.centralwidget)
        self.FileButton.setObjectName("FileButton")
        self.gridLayout.addWidget(self.FileButton, 0, 1, 1, 1)
        TEditWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(TEditWindow)
        self.statusBar.setObjectName("statusBar")
        TEditWindow.setStatusBar(self.statusBar)

        self.retranslateUi(TEditWindow)
        QtCore.QMetaObject.connectSlotsByName(TEditWindow)

    def retranslateUi(self, TEditWindow):
        _translate = QtCore.QCoreApplication.translate
        TEditWindow.setWindowTitle(_translate("TEditWindow", "Command Editor"))
        self.SaveButton.setText(_translate("TEditWindow", "Save"))
        self.CloseButton.setText(_translate("TEditWindow", "Close"))
        self.FileButton.setText(_translate("TEditWindow", "File"))
